version: '3.9'

services:
  python:
    build: ./python
    container_name: stock-generator
    volumes:
      - ./shared:/app/output
    environment:
      - SLEEP_SECONDS=60  # 24 hours
    restart: on-failure

  nginx:
    image: nginx:latest
    container_name: stock-server
    ports:
      - "8080:80"
    volumes:
      - ./shared:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
