version: '3.9'

services:
  python:
    build: ./python
    container_name: stock-generator
    volumes:
      - ./shared:/app/output
    environment:
      - SLEEP_SECONDS=60  # 1 minute
      - DEBUG=true
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=your-influxdb-token
      - INFLUX_ORG=wangpeihu-albert
      - INFLUX_BUCKET=stock_kpi
    depends_on:
      - influxdb
    restart: on-failure

  nginx:
    image: nginx:latest
    container_name: stock-server
    ports:
      - "8080:80"
    volumes:
      - ./shared:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=wangpeihu-albert
      - DOCKER_INFLUXDB_INIT_BUCKET=stock_kpi
      - DOCKER_INFLUXDB_INIT_TOKEN=your-influxdb-token
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    depends_on:
      - influxdb
    restart: unless-stopped

volumes:
  influxdb_data:
  grafana_data:
